import pygame
jojo = pygame.image.load('img/jojo1.jpg')
dio = pygame.image.load('img/dio.jpg')
real_dio = pygame.image.load('img/real_dio.jpg')
start_bg = pygame.image.load('img/start_bg.png')
bg_2 = pygame.image.load('img/bg_2.png')
school = pygame.image.load('img/school.png')
sprite_1 = pygame.image.load('img/sprite_1.png')
school500 = pygame.image.load('img/school500.png')
sprite500 = pygame.image.load('img/sprite500.png')
mylogo = pygame.image.load('img/mylogo')
down_1 = pygame.image.load('img/down_1.png')
